# Generated by Django 4.1.5 on 2023-03-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_follower_follower_alter_follower_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='follower',
            name='followed_at',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='following',
            name='followed_at',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
